### ISSUE TITLE
Review Tools: CSS max-width display issue

### ISSUE THREAD

**Issue by erosman** [mozilla/addons#1255]
Recent changes of `max-width:120em;` setting does not work best on all monitor (e.g. 4:3).

`https://addons.cdn.mozilla.net/static/css/zamboni/reviewers-min.css?build=1ad4576`

```css
.section,
.section .amo-header-wrapper {
 max-width:120em;
 width:auto
}

```
`https://addons.cdn.mozilla.net/static/css/zamboni/devhub-min.css?build=2b97598`
```css
.section {
 max-width:75em
}
```

![image](https://user-images.githubusercontent.com/6458876/94951845-dc9f7800-04f1-11eb-8510-940c2d96c02d.png)
