### ISSUE TITLE
Fix download button yello arrow style

### ISSUE THREAD

**Issue by willdurand** [mozilla/addons#14098]
Feedback from @verdi on Slack. We should add this:

```scss
.GetFirefoxButton-callout-icon {
	align-self: center;
}

.GetFirefoxButton-callout {
	border-radius: 4px;
}
```
