### ISSUE TITLE
Server response is inconsistent with the documentation

### ISSUE THREAD

**Issue by avi12** [mozilla/addons#1448]
### Describe the problem and steps to reproduce it:
For the given Node.js code:
```ts
const formData = new FormData();
formData.append("channel", "listed");
formData.append("upload", fs.createReadStream(xpiPath));
const response = await axios.post("https://addons.mozilla.org/api/v5/addons/upload", formData, {
  headers: {
    Authorization: `JWT ${token}`,
    "Content-Type": "multipart/form-data"
  }
});
console.log(response.data);
```
I'm getting:
```yaml
{
  page_size: 25, 
  page_count: 1, 
  count: 0,      
  next: null,    
  previous: null,
  results: [] 
}
```

### What did you expect to happen?
According to the [documentation](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-create), I'm supposed to get a [response](https://addons-server.readthedocs.io/en/latest/topics/api/addons.html#upload-detail-object) of the JSON structure:
```json
{
  "uuid": "",
  "channel": "listed",
  "processed": true,
  "submitted": true,
  "url": "",
  "valid": true,
  "validation": {},
  "version": ""
}
```
