### ISSUE TITLE
[Bug]: elasticsearch takes too long downloading geoip database, causing a timeout

### ISSUE THREAD

**Issue by eviljeff** [mozilla/addons#15275]
### What happened?

In local development sometimes `make up` fails for me, because the elasticsearch container isn't ready (healthy) before the timeout. After providing logs, @diox says:
> interesting that it's trying to download geoip database, we don't need that, and that's causing the startup to be slow
> a quick google search tells me we should be able to disable that with `ingest.geoip.downloader.enabled: false`

### What did you expect to happen?

A healthy elasticsearch container

### Is there an existing issue for this?

- [X] I have searched the existing issues

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/AMOENG-1346)

**Comment by diox** [comment]
We should try to stick that config bit in `docker-compose.yml` file and see if that works or if we need to do something else.

**Comment by eviljeff** [comment]
my docker-compose.yml looks like:
```
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.3
    environment:
      # Disable all xpack related features to avoid unrelated logging
      # in docker logs. https://github.com/mozilla/addons-server/issues/8887
      # This also avoids us to require authentication for local development
      # which simplifies the setup.
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ingest.geoip.downloader.enabled=false
    mem_limit: 2g
```
but elasticsearch still takes too long to load, leading to a timeout
