### ISSUE TITLE
Add bi-directional SCSS mixins

### ISSUE THREAD

**Issue by mstriemer** [mozilla/addons#9824]
Using `padding`, `margin`, `left` and `right` makes RTL support a bit tricky and consistently pops up bugs. We should add some mixins to make it easier to work with these CSS properties. There are [suggestions in a comment](https://github.com/mozilla/addons-frontend/pull/952#discussion_r75709028) along with some JS Bin links but here's the gist:

``` scss
@mixin bidi-margin($top, $end, $bottom, $start) {
  margin: $top $end $bottom $start;

  [dir=rtl] & {
    margin: $top $start $bottom $end;
  }
}

@mixin bidi-padding($top, $end, $bottom, $start) {
  padding: $top $end $bottom $start;

  [dir=rtl] & {
    padding: $top $start $bottom $end;
  }
}

@mixin bidi-start($offset) {
  left: $offset;
  right: auto;

  [dir=rtl] & {
    left: auto;
    right: $offset;
  }
}

@mixin bidi-end($offset) {
  left: auto;
  right: $offset;

  [dir=rtl] & {
    left: $offset;
    right: auto;
  }
}
```

Once these mixins are added the old code that is doing this by hand should be updated.
